version: "3.9"
services:
  speedflux:
    restart: always 
    build: .
    environment: 
        - NAMESPACE=${NAMESPACE}
        - INFLUX_DB_ADDRESS=${INFLUX_DB_ADDRESS}
        - INFLUX_DB_PORT=${INFLUX_DB_PORT}
        - INFLUX_DB_USER=${INFLUX_DB_USER}
        - INFLUX_DB_PASSWORD=${INFLUX_DB_PASSWORD}
        - INFLUX_DB_DATABASE=${INFLUX_DB_DATABASE}
        - INFLUX_DB_TAGS=${INFLUX_DB_TAGS}
        - SPEEDTEST_INTERVAL=${SPEEDTEST_INTERVAL}
        - PING_INTERVAL=${PING_INTERVAL}
        - PING_TARGETS=${PING_TARGETS}
        - LOG_TYPE=${LOG_TYPE}
    image: speedflux
