version: "3.9"
services:
  speedflux:
    build: .
    environment: 
        - NAMESPACE= None
        - INFLUX_DB_ADDRESS=[ip or hostname]
        - INFLUX_DB_PORT=[8086]
        - INFLUX_DB_USER=[db username]
        - INFLUX_DB_PASSWORD=[db password]
        - INFLUX_DB_DATABASE=speedtest
        - INFLUX_DB_TAGS=[select tags or empty] # See https://github.com/breadlysm/speedtest-to-influxdb#tag-options for details
        - SPEEDTEST_INTERVAL=150 # Minutes between speedtest updates. 
        - PING_INTERVAL=60 # Seconds between ping updates
        - PING_TARGETS=1.1.1.1, 8.8.8.8 # csv of hostnames to ping
        - LOG_TYPE=info
    image: speedflux
  