{
 "title": "SpeedTests",
 "description": "A dashboard to display speedtest data over time.",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "SHOW TAG VALUES FROM ping WITH Key = \"namespace\""
   }
  ]
 },
 "panels": [
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "download",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Test Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "download",
     "select": [
      [
       { "params": [ "elapsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Download Size Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "download",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Speedtest Results",
   "type": "graph",
   "description": "Uses https://github.com/breadlysm/speedtest-to-influxdb",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "download",
     "query": "SELECT mean(\"bytes\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "upload",
     "query": "SELECT mean(\"bytes\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Upload Size Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Leaders (Green) & Laggers (Yellow)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "measurement": "download",
     "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Down Mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "speedtest_url" ], "type": "tag" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       { "params": [ "Up Mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "speedtest_url" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       { "params": [ "Latency ms" ], "type": "alias" }
      ],
      [
       { "params": [ "jitter" ], "type": "field" },
       { "params": [ "Jitter ms" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Latency ms" ], "type": "alias" }
      ],
      [
       { "params": [ "jitter" ], "type": "field" },
       { "params": [ "Jitter ms" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "speedtest_url" ], "type": "tag" }
     ],
     "measurement": "download",
     "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       { "params": [ "Down Mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "speedtest_url" ], "type": "tag" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       { "params": [ "Up Mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "measurement": "download",
     "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "Down Mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "speedtest_url" ], "type": "tag" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       { "params": [ "Up Mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "speedtest_url" ], "type": "tag" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       { "params": [ "Latency ms" ], "type": "alias" }
      ],
      [
       { "params": [ "jitter" ], "type": "field" },
       { "params": [ "Jitter ms" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "measurement": "ping",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Latency ms" ], "type": "alias" }
      ],
      [
       { "params": [ "jitter" ], "type": "field" },
       { "params": [ "Jitter ms" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "speedtest_url" ], "type": "tag" }
     ],
     "measurement": "download",
     "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       { "params": [ "Down Mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "speedtest_url" ], "type": "tag" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "bandwidth" ], "type": "field" },
       { "params": [ "Up Mbps" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
     ]
    }
   ]
  },
  {
   "title": "Averages by Test Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "description": "Shows the avg speeds received by test site",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "Mbits" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "server_name" ], "type": "tag" },
        { "params": [ "server_location" ], "type": "tag" },
        { "params": [ "server_id" ], "type": "tag" }
       ],
       "measurement": "download",
       "query": "SELECT mean(\"bandwidth\") AS \"Download Avg\" FROM \"download\" WHERE $timeFilter GROUP BY \"server_name\", \"server_location\"",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Download Avg" ], "type": "alias" }
        ],
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         { "params": [ "Test Count" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "server_id" ], "type": "tag" }
       ],
       "measurement": "upload",
       "query": "SELECT mean(\"bandwidth\") AS \"Upload Avg\" FROM \"upload\" WHERE $timeFilter GROUP BY \"server_id\"",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Upload Avg" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "server_id" ], "type": "tag" }
       ],
       "measurement": "ping",
       "query": "SELECT mean(\"bandwidth\") AS \"Upload Avg\" FROM \"upload\" WHERE $timeFilter GROUP BY \"server_id\"",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "Ping" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Raw Results & Links",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Raw",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "download",
       "query": "SELECT max(\"bandwidth\") AS \"Down Mbps\" FROM \"download\" WHERE (\"namespace\" =~ /^$namespace$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Down Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "upload",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         { "params": [ "Up Mbps" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "speedtest_url" ], "type": "tag" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "latency" ], "type": "field" },
         { "params": [ "Latency ms" ], "type": "alias" }
        ],
        [
         { "params": [ "jitter" ], "type": "field" },
         { "params": [ "Jitter ms" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "namespace", "operator": "=~", "value": "/^$namespace$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}